"""SP-8 Phase E — TOTP hardware confirm.

Spec §10. Wrap pyotp with:

* ``setup()`` — generate a fresh secret + 10 backup codes; render a
  provisioning URI a QR code generator can consume.
* ``verify(secret, code)`` — accept a TOTP code with a 30s grace
  window for clock skew (one previous + one current step).
* ``LockoutTracker`` — in-memory failed-attempt counter with a 1-hour
  cooldown after 5 fails (spec §10.4).

The QR code itself is generated by the caller (frontend) from the
``otpauth://`` URI; backend doesn't need PIL/qrcode for this.
"""
from __future__ import annotations

import secrets as stdlib_secrets
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import ClassVar

import pyotp


_TOTP_INTERVAL_SECONDS = 30
_TOTP_GRACE_WINDOW = 1  # accept previous step too (=30s extra grace)
_BACKUP_CODE_COUNT = 10
_BACKUP_CODE_LEN = 10  # alphanumeric chars per backup code
_LOCKOUT_FAILS = 5
_LOCKOUT_WINDOW_MINUTES = 10
_LOCKOUT_DURATION_HOURS = 1


@dataclass(frozen=True)
class TOTPSetup:
    """Result of TOTP enrollment.

    The user scans the provisioning URI as a QR code in their authenticator
    app, then keeps the backup codes in a password manager. ``secret`` and
    ``backup_codes`` should be encrypted before persistence (see vault.py).
    """

    secret: str
    provisioning_uri: str
    backup_codes: list[str]


def setup(
    *, account_email: str, issuer: str = "trading-radar",
) -> TOTPSetup:
    """Enroll a user. Returns the new secret + URI + backup codes."""
    secret = pyotp.random_base32()
    totp = pyotp.TOTP(secret, interval=_TOTP_INTERVAL_SECONDS)
    uri = totp.provisioning_uri(name=account_email, issuer_name=issuer)
    backup_codes = [
        stdlib_secrets.token_urlsafe(_BACKUP_CODE_LEN)[:_BACKUP_CODE_LEN].upper()
        for _ in range(_BACKUP_CODE_COUNT)
    ]
    return TOTPSetup(secret=secret, provisioning_uri=uri, backup_codes=backup_codes)


def verify(
    secret: str, code: str,
    *,
    now: datetime | None = None,
) -> bool:
    """Verify a 6-digit TOTP code with a one-step grace window.

    The grace window accepts codes from the previous 30s step too,
    handling clock skew between the user's device and the server.
    Codes outside ±1 step are rejected.

    Args:
        secret: base32-encoded TOTP secret produced by ``setup()``.
        code: the 6-digit code the user typed.
        now: timestamp to verify against (default: real wall clock).
            Injectable for deterministic tests.
    """
    if not code or not code.isdigit() or len(code) != 6:
        return False
    totp = pyotp.TOTP(secret, interval=_TOTP_INTERVAL_SECONDS)
    target_t = (now or datetime.now(timezone.utc)).timestamp()
    return totp.verify(code, for_time=target_t, valid_window=_TOTP_GRACE_WINDOW)


def verify_backup_code(
    stored_codes: list[str], submitted: str,
) -> tuple[bool, list[str]]:
    """One-time backup code use. Returns (matched, remaining_codes).

    The matched code is removed from the returned list so the caller
    persists the consumed state. Comparison is case-insensitive.
    """
    target = (submitted or "").strip().upper()
    if not target:
        return False, stored_codes
    remaining = list(stored_codes)
    for i, c in enumerate(remaining):
        if c.upper() == target:
            del remaining[i]
            return True, remaining
    return False, stored_codes


@dataclass
class LockoutTracker:
    """In-memory per-user failed-attempt tracker.

    Spec §10.4: 5 failed confirms in 10 min → lock 1 hour. After lockout
    expires, the counter resets.

    Production wiring keeps one instance per process (lifespan-scoped).
    Multi-process deploys would need a shared store (Redis); single-uvicorn
    is fine for now.
    """

    fails: dict[int, list[datetime]] = field(default_factory=lambda: defaultdict(list))
    locks: dict[int, datetime] = field(default_factory=dict)

    LOCKOUT_FAILS: ClassVar[int] = _LOCKOUT_FAILS
    LOCKOUT_WINDOW_MINUTES: ClassVar[int] = _LOCKOUT_WINDOW_MINUTES
    LOCKOUT_DURATION_HOURS: ClassVar[int] = _LOCKOUT_DURATION_HOURS

    def is_locked(self, user_id: int, *, now: datetime | None = None) -> bool:
        n = now or datetime.now(timezone.utc)
        unlock = self.locks.get(user_id)
        if unlock is None:
            return False
        if unlock <= n:
            del self.locks[user_id]
            self.fails[user_id] = []
            return False
        return True

    def record_fail(
        self, user_id: int, *, now: datetime | None = None,
    ) -> bool:
        """Record a failed attempt. Returns True if the user is now locked."""
        n = now or datetime.now(timezone.utc)
        if self.is_locked(user_id, now=n):
            return True
        cutoff = n - timedelta(minutes=_LOCKOUT_WINDOW_MINUTES)
        recent = [t for t in self.fails[user_id] if t > cutoff]
        recent.append(n)
        self.fails[user_id] = recent
        if len(recent) >= _LOCKOUT_FAILS:
            self.locks[user_id] = n + timedelta(hours=_LOCKOUT_DURATION_HOURS)
            return True
        return False

    def record_success(self, user_id: int) -> None:
        """Clear all fails + lock for this user."""
        self.fails.pop(user_id, None)
        self.locks.pop(user_id, None)


__all__ = [
    "TOTPSetup",
    "LockoutTracker",
    "setup",
    "verify",
    "verify_backup_code",
]
